/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;


import ConectorDB.Conexion;
import java.awt.Graphics;
import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author PC
 */
public class Laboratorios extends javax.swing.JFrame {
    FondoPanel fondo = new FondoPanel();
    

    /**
     * Creates new form Laboratorios
     */
    
    
    public Laboratorios() {
        this.setContentPane(fondo);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(this.MAXIMIZED_BOTH);
        updateCombo();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_return = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLA_DATOS = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txt_cod_lab = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TXT_Nombre_repartidor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TXT_Apellido_repartidor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_RUC_Lab = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_TELEFONO = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_Busqueda = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        BTN_ELIMINAR = new javax.swing.JButton();
        BTN_MODIFICAR = new javax.swing.JButton();
        BTN_CONFIRMAR = new javax.swing.JButton();
        BTN_LISTAR = new javax.swing.JButton();
        BTN_REGISTRAR4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txt_marca = new javax.swing.JTextField();
        Jcombo_sedes = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_return.setFont(new java.awt.Font("Perpetua Titling MT", 0, 24)); // NOI18N
        btn_return.setText("Regresar");
        btn_return.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_returnActionPerformed(evt);
            }
        });
        getContentPane().add(btn_return, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 857, 202, 67));

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Laboratorios Asociados");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 37, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingrese los datos requeridos:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 98, -1, -1));

        TABLA_DATOS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo de Laboratorio", "Nombre del Repartidor", "Apellido del Repartidor", "RUC", "MARCA", "TELEFONO", "CODIGO DE SEDE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TABLA_DATOS.setRowHeight(30);
        jScrollPane1.setViewportView(TABLA_DATOS);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 519, 1179, 306));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Código del Laboratorio:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 156, -1, -1));

        txt_cod_lab.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(txt_cod_lab, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 151, 194, 41));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre del distribuidor:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 215, -1, -1));

        TXT_Nombre_repartidor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(TXT_Nombre_repartidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 210, 259, 41));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Apellido del distribuidor:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 274, -1, -1));

        TXT_Apellido_repartidor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(TXT_Apellido_repartidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 269, 259, 41));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("RUC del Laboratorio:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 333, -1, -1));

        txt_RUC_Lab.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(txt_RUC_Lab, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 328, 259, 41));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Marca:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 150, -1, -1));

        txt_TELEFONO.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(txt_TELEFONO, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 200, 279, 41));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Telefono:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, -1, -1));

        txt_Busqueda.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(txt_Busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 330, 279, 41));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Buscar");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 340, -1, -1));

        BTN_ELIMINAR.setFont(new java.awt.Font("Perpetua Titling MT", 0, 24)); // NOI18N
        BTN_ELIMINAR.setText("Eliminar");
        BTN_ELIMINAR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTN_ELIMINAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ELIMINARActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_ELIMINAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 398, 202, 67));

        BTN_MODIFICAR.setFont(new java.awt.Font("Perpetua Titling MT", 0, 24)); // NOI18N
        BTN_MODIFICAR.setText("Modificar");
        BTN_MODIFICAR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTN_MODIFICAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_MODIFICARActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_MODIFICAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 398, 202, 67));

        BTN_CONFIRMAR.setFont(new java.awt.Font("Perpetua Titling MT", 0, 24)); // NOI18N
        BTN_CONFIRMAR.setText("Confirmar");
        BTN_CONFIRMAR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTN_CONFIRMAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_CONFIRMARActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_CONFIRMAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(771, 398, 202, 67));

        BTN_LISTAR.setFont(new java.awt.Font("Perpetua Titling MT", 0, 24)); // NOI18N
        BTN_LISTAR.setText("Listar");
        BTN_LISTAR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTN_LISTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_LISTARActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_LISTAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(991, 398, 202, 67));

        BTN_REGISTRAR4.setFont(new java.awt.Font("Perpetua Titling MT", 0, 24)); // NOI18N
        BTN_REGISTRAR4.setText("REGISTRAR");
        BTN_REGISTRAR4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTN_REGISTRAR4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_REGISTRAR4ActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_REGISTRAR4, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 398, 202, 67));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Codigo de sede:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, -1, -1));

        txt_marca.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(txt_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 150, 279, 41));

        Jcombo_sedes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Jcombo_sedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jcombo_sedesActionPerformed(evt);
            }
        });
        getContentPane().add(Jcombo_sedes, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 270, 271, 48));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_returnActionPerformed
        Menu MN = new Menu();
        MN.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_returnActionPerformed

    private void BTN_ELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ELIMINARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_ELIMINARActionPerformed

    private void BTN_MODIFICARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_MODIFICARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_MODIFICARActionPerformed

    private void BTN_CONFIRMARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_CONFIRMARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_CONFIRMARActionPerformed

    private void BTN_LISTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_LISTARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_LISTARActionPerformed

    private void BTN_REGISTRAR4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_REGISTRAR4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_REGISTRAR4ActionPerformed

    private void Jcombo_sedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jcombo_sedesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jcombo_sedesActionPerformed
    private void updateCombo(){
        Statement st;
        Conexion con = new Conexion();
        Connection conexion = con.getConexion();
        String sql  = "select * from sucursales ";
        try {
                st=conexion.prepareStatement(sql);
                ResultSet rs = st.executeQuery(sql);
                while(rs.next()){
                    Jcombo_sedes.addItem(rs.getString("cod_sucursal"));
                }
            } catch (Exception e) {
            }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laboratorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laboratorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laboratorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laboratorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laboratorios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BTN_CONFIRMAR;
    public javax.swing.JButton BTN_ELIMINAR;
    public javax.swing.JButton BTN_LISTAR;
    public javax.swing.JButton BTN_MODIFICAR;
    public javax.swing.JButton BTN_REGISTRAR4;
    public javax.swing.JComboBox<String> Jcombo_sedes;
    public javax.swing.JTable TABLA_DATOS;
    public javax.swing.JTextField TXT_Apellido_repartidor;
    public javax.swing.JTextField TXT_Nombre_repartidor;
    public javax.swing.JButton btn_return;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField txt_Busqueda;
    public javax.swing.JTextField txt_RUC_Lab;
    public javax.swing.JTextField txt_TELEFONO;
    public javax.swing.JTextField txt_cod_lab;
    public javax.swing.JTextField txt_marca;
    // End of variables declaration//GEN-END:variables
class FondoPanel extends JPanel
    {
        private Image imagen;
        
        @Override
        public void paint(Graphics g)
        {
            imagen = new ImageIcon(getClass().getResource("/Pictures/labo.png")).getImage();
            
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            
            setOpaque(false);
            
            super.paint(g);
        }
    }
}
