/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorCRUD_Empleados;
import Controlador.ControladorCRUD_Laboratorio;
import Controlador.ControladorCRUD_Pacientes;
import Controlador.ControladorCRUD_Productos;
import Controlador.ControladorCRUD_Ventas;
import Controlador.ControladorCrud;
import Modelo_Empleados.EmpleadoDAO;
import Modelo_Laboratorio.LaboratorioDAO;
import Modelo_Pacientes.PacienteDAO;
import Modelo_Productos.ProductosDAO;
import Modelo_Sucursal.SucursalDAO;
import Modelo_Ventas.VentasDAO;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author PC
 */
public class Menu extends javax.swing.JFrame {
    FondoPanel fondo = new FondoPanel();

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(this.MAXIMIZED_BOTH);
        rsscalelabel.RSScaleLabel.setScaleLabel(imagen1, "src/Pictures/imagen1.jpeg");
        rsscalelabel.RSScaleLabel.setScaleLabel(imagen2, "src/Pictures/imagen2.jpeg");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        izq = new javax.swing.JPanel();
        btn_Cerrar_Sesion = new javax.swing.JButton();
        btn_Sucursales = new javax.swing.JButton();
        btn_Laboratorios = new javax.swing.JButton();
        btn_Productos = new javax.swing.JButton();
        btn_Empleados = new javax.swing.JButton();
        btn_Pacientes = new javax.swing.JButton();
        btn_Ventas = new javax.swing.JButton();
        Registrar_Nuevo_Usuario = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        imagen1 = new javax.swing.JLabel();
        imagen2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        izq.setBackground(new java.awt.Color(51, 153, 255));
        izq.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        izq.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Cerrar_Sesion.setBackground(new java.awt.Color(255, 102, 102));
        btn_Cerrar_Sesion.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        btn_Cerrar_Sesion.setText("Cerrar Sesión");
        btn_Cerrar_Sesion.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 51)));
        btn_Cerrar_Sesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Cerrar_Sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Cerrar_SesionActionPerformed(evt);
            }
        });
        izq.add(btn_Cerrar_Sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 810, 320, 70));

        btn_Sucursales.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        btn_Sucursales.setText("Nuestras Sucursales");
        btn_Sucursales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Sucursales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SucursalesActionPerformed(evt);
            }
        });
        izq.add(btn_Sucursales, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 320, 70));

        btn_Laboratorios.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        btn_Laboratorios.setText("Abastecimiento");
        btn_Laboratorios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Laboratorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LaboratoriosActionPerformed(evt);
            }
        });
        izq.add(btn_Laboratorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 320, 70));

        btn_Productos.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        btn_Productos.setText("Productos");
        btn_Productos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ProductosActionPerformed(evt);
            }
        });
        izq.add(btn_Productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 320, 70));

        btn_Empleados.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        btn_Empleados.setText("Empleados");
        btn_Empleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EmpleadosActionPerformed(evt);
            }
        });
        izq.add(btn_Empleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 320, 70));

        btn_Pacientes.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        btn_Pacientes.setText("Pacientes");
        btn_Pacientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Pacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PacientesActionPerformed(evt);
            }
        });
        izq.add(btn_Pacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 320, 70));

        btn_Ventas.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        btn_Ventas.setText("Resultados");
        btn_Ventas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VentasActionPerformed(evt);
            }
        });
        izq.add(btn_Ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 320, 70));

        Registrar_Nuevo_Usuario.setBackground(new java.awt.Color(153, 255, 153));
        Registrar_Nuevo_Usuario.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        Registrar_Nuevo_Usuario.setText("Registrar Nuevo Usuario");
        Registrar_Nuevo_Usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Registrar_Nuevo_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Registrar_Nuevo_UsuarioActionPerformed(evt);
            }
        });
        izq.add(Registrar_Nuevo_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 710, 320, 70));

        jButton1.setBackground(new java.awt.Color(51, 255, 204));
        jButton1.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        jButton1.setText("Contactenos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        izq.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, 320, 70));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(153, 51, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Informacion sobre nosotros y nuestra funcionalidad");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1193, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        imagen1.setBackground(new java.awt.Color(102, 204, 255));
        imagen1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        imagen1.setOpaque(true);

        imagen2.setBackground(new java.awt.Color(153, 255, 255));
        imagen2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        imagen2.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2.setText("<html><left>La clínica se compromete plenamente a prestar atención médica de calidad y promover el bienestar integral de sus pacientes. Nuestro compromiso se basa en brindar un ambiente acogedor y seguro, donde cada individuo sea tratado con respeto, compasión y empatía. Nos esforzamos por mantener altos estándares éticos y profesionales en todas nuestras prácticas, asegurando la confidencialidad y privacidad de la información médica de nuestros pacientes. Además, nos comprometemos a mantenernos actualizados con los avances médicos y tecnológicos, invirtiendo en capacitación continua y en la adquisición de equipos de vanguardia para ofrecer diagnósticos precisos y tratamientos efectivos. Nuestro objetivo principal es mejorar la salud y el bienestar de nuestros pacientes, proporcionándoles una atención integral y personalizada que aborde sus necesidades individuales de manera integral. Estamos comprometidos a establecer relaciones de confianza a largo plazo con nuestros pacientes, brindando un cuidado de calidad y siendo un socio confiable en su viaje hacia una vida saludable.");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setText("<html><left>La clínica se destaca por su funcionalidad excepcional, diseñada para optimizar la atención médica y satisfacer las necesidades de nuestros pacientes. Contamos con un equipo médico altamente capacitado y especializado en diversas áreas de la salud, lo que nos permite ofrecer una amplia gama de servicios y tratamientos. Nuestras instalaciones están equipadas con tecnología de última generación, lo que nos permite realizar diagnósticos precisos y ofrecer los tratamientos más avanzados. Además, nuestra clínica se enfoca en garantizar una atención eficiente y oportuna, mediante la implementación de sistemas de gestión que optimizan los tiempos de espera y agilizan los procesos administrativos.Nuestro objetivo es brindar a nuestros pacientes una experiencia fluida y cómoda desde el momento en que ingresan a nuestras instalaciones. Valoramos la accesibilidad y la comodidad, por lo que nos esforzamos por ofrecer horarios flexibles, servicios en línea y un equipo de atención al cliente amable y dispuesto a ayudar en todo momento.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(imagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(359, 359, 359)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(imagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(izq, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(izq, javax.swing.GroupLayout.DEFAULT_SIZE, 913, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SucursalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SucursalesActionPerformed
        Sucursales vistaC = new Sucursales();
        SucursalDAO modeloC = new SucursalDAO();
        ControladorCrud controlac = new ControladorCrud(vistaC,modeloC);
        vistaC.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_SucursalesActionPerformed

    private void btn_LaboratoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LaboratoriosActionPerformed
        Laboratorios vistaC = new Laboratorios();
        LaboratorioDAO modeloC = new LaboratorioDAO();
        ControladorCRUD_Laboratorio controlac = new ControladorCRUD_Laboratorio(vistaC,modeloC);
        vistaC.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_LaboratoriosActionPerformed

    private void btn_ProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ProductosActionPerformed
        Productos vistaC = new Productos();
        ProductosDAO modeloC = new ProductosDAO();
        ControladorCRUD_Productos controlac = new ControladorCRUD_Productos(vistaC,modeloC);
        vistaC.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_ProductosActionPerformed

    private void btn_EmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EmpleadosActionPerformed
        Empleados vistaC = new Empleados();
        EmpleadoDAO modeloC = new EmpleadoDAO();
        ControladorCRUD_Empleados controlac = new ControladorCRUD_Empleados(vistaC,modeloC);
        vistaC.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_EmpleadosActionPerformed

    private void btn_PacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PacientesActionPerformed
        Pacientes vistaC = new Pacientes();
        PacienteDAO modeloC = new PacienteDAO();
        ControladorCRUD_Pacientes controlac = new ControladorCRUD_Pacientes(vistaC,modeloC);
        vistaC.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_PacientesActionPerformed

    private void btn_Cerrar_SesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Cerrar_SesionActionPerformed
        JOptionPane.showMessageDialog(null, "Se cerró la Sesión con Exito");
        System.exit(0);
    }//GEN-LAST:event_btn_Cerrar_SesionActionPerformed

    private void btn_VentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VentasActionPerformed
        Ventas vistaC = new Ventas();
        VentasDAO modeloC = new VentasDAO();
        ControladorCRUD_Ventas controlac = new ControladorCRUD_Ventas(vistaC,modeloC);
        vistaC.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_VentasActionPerformed

    private void Registrar_Nuevo_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Registrar_Nuevo_UsuarioActionPerformed
        String password = JOptionPane.showInputDialog(this, "Ingrese la contraseña:", "Autenticación", JOptionPane.PLAIN_MESSAGE);

    if ("admin1".equals(password)) {
        Registro R = new Registro();
        R.setVisible(true);
        dispose();
    } else {
        JOptionPane.showMessageDialog(this, "Contraseña incorrecta.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_Registrar_Nuevo_UsuarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:EmailSenderFrame
        EmailSenderFrame email = new EmailSenderFrame();
        email.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Registrar_Nuevo_Usuario;
    private javax.swing.JButton btn_Cerrar_Sesion;
    private javax.swing.JButton btn_Empleados;
    private javax.swing.JButton btn_Laboratorios;
    private javax.swing.JButton btn_Pacientes;
    private javax.swing.JButton btn_Productos;
    private javax.swing.JButton btn_Sucursales;
    private javax.swing.JButton btn_Ventas;
    private javax.swing.JLabel imagen1;
    private javax.swing.JLabel imagen2;
    private javax.swing.JPanel izq;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
class FondoPanel extends JPanel
    {
        private Image imagen;
        
        @Override
        public void paint(Graphics g)
        {
            imagen = new ImageIcon(getClass().getResource("/Pictures/fondo_login.png")).getImage();
            
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            
            setOpaque(false);
            
            super.paint(g);
        }
    }

}
