/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import ConectorDB.Conexion;
import com.itextpdf.text.pdf.PdfPCell;
import java.awt.Graphics;
import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import java.sql.PreparedStatement;
import java.sql.SQLException;


/**
 *
 * @author PC
 */
public class Productos extends javax.swing.JFrame {
FondoPanel fondo = new FondoPanel();
    /**
     * Creates new form Productos
     */
    public Productos() {
        this.setContentPane(fondo);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(this.MAXIMIZED_BOTH);
        updateCombo();
        updateCombo2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_return = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLA_DATOS = new javax.swing.JTable();
        BTN_REGISTRAR = new javax.swing.JButton();
        BTN_MODIFICAR = new javax.swing.JButton();
        BTN_ELIMINAR = new javax.swing.JButton();
        BTN_Confirmar = new javax.swing.JButton();
        BTN_LISTAR = new javax.swing.JButton();
        txt_cod_prod = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_Nombre = new javax.swing.JTextField();
        Jcombo_sedes = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_cantidad = new javax.swing.JTextField();
        txt_precio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Jcombo_Marcas = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txt_Busqueda = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_return.setFont(new java.awt.Font("Perpetua Titling MT", 0, 24)); // NOI18N
        btn_return.setText("Regresar");
        btn_return.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_returnActionPerformed(evt);
            }
        });
        getContentPane().add(btn_return, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 850, 202, 67));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Ingrese los datos correctos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel2.setText("Nuestros Medicamentos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 6, -1, -1));

        TABLA_DATOS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo de Producto", "Nombre", "Cantidad", "Precio", "Total", "Marca", "Codigo de Sucursal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TABLA_DATOS.setRowHeight(30);
        jScrollPane1.setViewportView(TABLA_DATOS);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 1200, 350));

        BTN_REGISTRAR.setFont(new java.awt.Font("Perpetua Titling MT", 0, 24)); // NOI18N
        BTN_REGISTRAR.setText("Registrar");
        BTN_REGISTRAR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(BTN_REGISTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 354, 202, 67));

        BTN_MODIFICAR.setFont(new java.awt.Font("Perpetua Titling MT", 0, 24)); // NOI18N
        BTN_MODIFICAR.setText("Modificar");
        BTN_MODIFICAR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTN_MODIFICAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_MODIFICARActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_MODIFICAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 354, 202, 67));

        BTN_ELIMINAR.setFont(new java.awt.Font("Perpetua Titling MT", 0, 24)); // NOI18N
        BTN_ELIMINAR.setText("Eliminar");
        BTN_ELIMINAR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(BTN_ELIMINAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 354, 202, 67));

        BTN_Confirmar.setFont(new java.awt.Font("Perpetua Titling MT", 0, 24)); // NOI18N
        BTN_Confirmar.setText("Confirmar");
        BTN_Confirmar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(BTN_Confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(789, 354, 202, 67));

        BTN_LISTAR.setFont(new java.awt.Font("Perpetua Titling MT", 0, 24)); // NOI18N
        BTN_LISTAR.setText("Listar");
        BTN_LISTAR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(BTN_LISTAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(1031, 354, 202, 67));

        txt_cod_prod.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(txt_cod_prod, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 194, 41));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Código del Producto:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Nombre:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Código de Sucursal:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        txt_Nombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(txt_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 194, 41));

        Jcombo_sedes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Jcombo_sedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jcombo_sedesActionPerformed(evt);
            }
        });
        getContentPane().add(Jcombo_sedes, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 194, 48));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("Precio:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, -1, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Cantidad:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, -1, 30));

        txt_cantidad.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(txt_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, 146, 40));

        txt_precio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(txt_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, 161, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("Marca:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, -1, 30));

        Jcombo_Marcas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Jcombo_Marcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jcombo_MarcasActionPerformed(evt);
            }
        });
        getContentPane().add(Jcombo_Marcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 280, 267, 50));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setText("Buscar Nombre:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 290, -1, 30));

        txt_Busqueda.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(txt_Busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 290, 230, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_returnActionPerformed
        Menu MN = new Menu();
        MN.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_returnActionPerformed

    private void BTN_MODIFICARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_MODIFICARActionPerformed

    }//GEN-LAST:event_BTN_MODIFICARActionPerformed

    private void Jcombo_sedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jcombo_sedesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jcombo_sedesActionPerformed

    private void Jcombo_MarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jcombo_MarcasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jcombo_MarcasActionPerformed

    private void updateCombo() {
    Conexion con = new Conexion();
    Connection conexion = con.getConexion();
    String sql = "SELECT * FROM sucursales";
    PreparedStatement ps = null;
    ResultSet rs = null;
    try {
        ps = conexion.prepareStatement(sql);
        rs = ps.executeQuery();
        Jcombo_sedes.removeAllItems(); // Limpiar antes de añadir elementos
        while (rs.next()) {
            Jcombo_sedes.addItem(rs.getString("cod_sucursal"));
        }
    } catch (SQLException e) {
        e.printStackTrace(); // Manejar excepción
    } finally {
        try {
            if (rs != null) rs.close();
            if (ps != null) ps.close();
            if (conexion != null) conexion.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}

private void updateCombo2() {
    Conexion con = new Conexion();
    Connection conexion = con.getConexion();
    String sql = "SELECT * FROM laboratorios";
    PreparedStatement ps = null;
    ResultSet rs = null;
    try {
        ps = conexion.prepareStatement(sql);
        rs = ps.executeQuery();
        Jcombo_Marcas.removeAllItems(); // Limpiar antes de añadir elementos
        while (rs.next()) {
            Jcombo_Marcas.addItem(rs.getString("Marca"));
        }
    } catch (SQLException e) {
        e.printStackTrace(); // Manejar excepción
    } finally {
        try {
            if (rs != null) rs.close();
            if (ps != null) ps.close();
            if (conexion != null) conexion.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BTN_Confirmar;
    public javax.swing.JButton BTN_ELIMINAR;
    public javax.swing.JButton BTN_LISTAR;
    public javax.swing.JButton BTN_MODIFICAR;
    public javax.swing.JButton BTN_REGISTRAR;
    public javax.swing.JComboBox<String> Jcombo_Marcas;
    public javax.swing.JComboBox<String> Jcombo_sedes;
    public javax.swing.JTable TABLA_DATOS;
    public javax.swing.JButton btn_return;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField txt_Busqueda;
    public javax.swing.JTextField txt_Nombre;
    public javax.swing.JTextField txt_cantidad;
    public javax.swing.JTextField txt_cod_prod;
    public javax.swing.JTextField txt_precio;
    // End of variables declaration//GEN-END:variables
class FondoPanel extends JPanel
    {
        private Image imagen;
        
        @Override
        public void paint(Graphics g)
        {
            imagen = new ImageIcon(getClass().getResource("/Pictures/productos.png")).getImage();
            
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            
            setOpaque(false);
            
            super.paint(g);
        }
    }
}
