/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import ConectorDB.Conexion;
import java.awt.Graphics;
import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author PC
 */
public class Ventas extends javax.swing.JFrame {
FondoPanel fondo = new FondoPanel();
    /**
     * Creates new form Ventas
     */
    public Ventas() {
        this.setContentPane(fondo);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(this.MAXIMIZED_BOTH);
        updateCombo();
        updateCombo2();
        updateCombo3();
        updateCombo4();
        //updateCombo5();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_return = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLA_DATOS = new javax.swing.JTable();
        BTN_REGISTRAR4 = new javax.swing.JButton();
        BTN_MODIFICAR = new javax.swing.JButton();
        BTN_ELIMINAR = new javax.swing.JButton();
        BTN_CONFIRMAR = new javax.swing.JButton();
        BTN_LISTAR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JdFecha = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        txt_busqueda = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Jcombo_cod_sede = new javax.swing.JComboBox<>();
        Jcombo_ape_paci = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Jcombo_ape_emple = new javax.swing.JComboBox<>();
        Jcombo_products = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        Jcombo_urg_nivel = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txt_cod_venta2 = new javax.swing.JTextField();
        BTN_DESCARGAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_return.setFont(new java.awt.Font("Perpetua Titling MT", 0, 24)); // NOI18N
        btn_return.setText("Regresar");
        btn_return.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_returnActionPerformed(evt);
            }
        });
        getContentPane().add(btn_return, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 890, 202, 67));

        TABLA_DATOS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo de Resultado", "Fecha", "Apellido de Empleado", "Apellido de Paciente", "Nombre del Producto", "Urgencia", "Codigo Sucursal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TABLA_DATOS.setRowHeight(30);
        jScrollPane1.setViewportView(TABLA_DATOS);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 1420, 273));

        BTN_REGISTRAR4.setFont(new java.awt.Font("Perpetua Titling MT", 0, 24)); // NOI18N
        BTN_REGISTRAR4.setText("REGISTRAR");
        BTN_REGISTRAR4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTN_REGISTRAR4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_REGISTRAR4ActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_REGISTRAR4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 202, 67));

        BTN_MODIFICAR.setFont(new java.awt.Font("Perpetua Titling MT", 0, 24)); // NOI18N
        BTN_MODIFICAR.setText("Modificar");
        BTN_MODIFICAR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTN_MODIFICAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_MODIFICARActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_MODIFICAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, 202, 67));

        BTN_ELIMINAR.setFont(new java.awt.Font("Perpetua Titling MT", 0, 24)); // NOI18N
        BTN_ELIMINAR.setText("Eliminar");
        BTN_ELIMINAR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTN_ELIMINAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ELIMINARActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_ELIMINAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, 202, 67));

        BTN_CONFIRMAR.setFont(new java.awt.Font("Perpetua Titling MT", 0, 24)); // NOI18N
        BTN_CONFIRMAR.setText("Confirmar");
        BTN_CONFIRMAR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTN_CONFIRMAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_CONFIRMARActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_CONFIRMAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 490, 202, 67));

        BTN_LISTAR.setFont(new java.awt.Font("Perpetua Titling MT", 0, 24)); // NOI18N
        BTN_LISTAR.setText("Listar");
        BTN_LISTAR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTN_LISTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_LISTARActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_LISTAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 490, 202, 67));

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 0, 36)); // NOI18N
        jLabel1.setText("Resultados Finales");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 25, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Apellido de Paciente:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Código de Resultado:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));
        getContentPane().add(JdFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 250, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Buscar:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 400, -1, -1));

        txt_busqueda.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(txt_busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 390, 220, 50));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("Producto:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 180, -1, -1));

        Jcombo_cod_sede.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Jcombo_cod_sede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jcombo_cod_sedeActionPerformed(evt);
            }
        });
        getContentPane().add(Jcombo_cod_sede, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 320, 271, 50));

        Jcombo_ape_paci.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Jcombo_ape_paci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jcombo_ape_paciActionPerformed(evt);
            }
        });
        getContentPane().add(Jcombo_ape_paci, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 271, 50));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Apellido de Empleado:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("Fecha de Venta:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));

        Jcombo_ape_emple.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Jcombo_ape_emple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jcombo_ape_empleActionPerformed(evt);
            }
        });
        getContentPane().add(Jcombo_ape_emple, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 271, 50));

        Jcombo_products.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Jcombo_products.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jcombo_productsActionPerformed(evt);
            }
        });
        getContentPane().add(Jcombo_products, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 170, 271, 50));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setText("Nivel de Urgencia:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 240, -1, -1));

        Jcombo_urg_nivel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Jcombo_urg_nivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alto", "Moderado", "Bajo" }));
        Jcombo_urg_nivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jcombo_urg_nivelActionPerformed(evt);
            }
        });
        getContentPane().add(Jcombo_urg_nivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 240, 271, 50));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setText("Codigo de Sede:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 330, -1, -1));

        txt_cod_venta2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txt_cod_venta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cod_venta2ActionPerformed(evt);
            }
        });
        getContentPane().add(txt_cod_venta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 220, 50));

        BTN_DESCARGAR.setFont(new java.awt.Font("Perpetua Titling MT", 0, 24)); // NOI18N
        BTN_DESCARGAR.setText("DESCARGAR");
        BTN_DESCARGAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_DESCARGARActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_DESCARGAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 490, 200, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_returnActionPerformed
        Menu MN = new Menu();
        MN.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_returnActionPerformed

    private void BTN_REGISTRAR4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_REGISTRAR4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_REGISTRAR4ActionPerformed

    private void BTN_MODIFICARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_MODIFICARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_MODIFICARActionPerformed

    private void BTN_ELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ELIMINARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_ELIMINARActionPerformed

    private void BTN_CONFIRMARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_CONFIRMARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_CONFIRMARActionPerformed

    private void BTN_LISTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_LISTARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_LISTARActionPerformed

    private void Jcombo_cod_sedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jcombo_cod_sedeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jcombo_cod_sedeActionPerformed

    private void Jcombo_ape_paciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jcombo_ape_paciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jcombo_ape_paciActionPerformed

    private void Jcombo_ape_empleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jcombo_ape_empleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jcombo_ape_empleActionPerformed

    private void Jcombo_productsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jcombo_productsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jcombo_productsActionPerformed

    private void Jcombo_urg_nivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jcombo_urg_nivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jcombo_urg_nivelActionPerformed

    private void txt_cod_venta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cod_venta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cod_venta2ActionPerformed

    private void BTN_DESCARGARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_DESCARGARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_DESCARGARActionPerformed
private void updateCombo(){
        Statement st;
        Conexion con = new Conexion();
        Connection conexion = con.getConexion();
        String sql  = "select * from sucursales ";
        try {
                st=conexion.prepareStatement(sql);
                ResultSet rs = st.executeQuery(sql);
                while(rs.next()){
                    Jcombo_cod_sede.addItem(rs.getString("cod_sucursal"));
                }
            } catch (Exception e) {
            }
    }
private void updateCombo2(){
        Statement st;
        Conexion con = new Conexion();
        Connection conexion = con.getConexion();
        String sql  = "select * from empleados ";
        try {
                st=conexion.prepareStatement(sql);
                ResultSet rs = st.executeQuery(sql);
                while(rs.next()){
                    String apellido = rs.getString("emple_ape");
                    String otraColumna = rs.getString("Especialidad");
                    String valorCombo = apellido + " - " + otraColumna;
                    Jcombo_ape_emple.addItem(valorCombo);
                }
            } catch (Exception e) {
            }
    }
private void updateCombo3(){
        Statement st;
        Conexion con = new Conexion();
        Connection conexion = con.getConexion();
        String sql  = "select * from pacientes ";
        try {
                st=conexion.prepareStatement(sql);
                ResultSet rs = st.executeQuery(sql);
                while(rs.next()){
                    String apellido = rs.getString("Ape_Paciente");
                    String otraColumna = rs.getString("Enfermedad");
                    String valorCombo = apellido + " - " + otraColumna;
                    Jcombo_ape_paci.addItem(valorCombo);
                }
            } catch (Exception e) {
            }
    }
private void updateCombo4(){
        Statement st;
        Conexion con = new Conexion();
        Connection conexion = con.getConexion();
        String sql  = "select * from productos ";
        try {
                st=conexion.prepareStatement(sql);
                ResultSet rs = st.executeQuery(sql);
                while(rs.next()){
                    Jcombo_products.addItem(rs.getString("nombre"));
                }
            } catch (Exception e) {
            }
    }
/*private void updateCombo5(){
        Statement st;
        Conexion con = new Conexion();
        Connection conexion = con.getConexion();
        String sql  = "select * from urgencias ";
        try {
                st=conexion.prepareStatement(sql);
                ResultSet rs = st.executeQuery(sql);
                while(rs.next()){
                    Jcombo_urg_nivel.addItem(rs.getString("nivel_urgencia"));
                }
            } catch (Exception e) {
            }
    }*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BTN_CONFIRMAR;
    public javax.swing.JButton BTN_DESCARGAR;
    public javax.swing.JButton BTN_ELIMINAR;
    public javax.swing.JButton BTN_LISTAR;
    public javax.swing.JButton BTN_MODIFICAR;
    public javax.swing.JButton BTN_REGISTRAR4;
    public javax.swing.JComboBox<String> Jcombo_ape_emple;
    public javax.swing.JComboBox<String> Jcombo_ape_paci;
    public javax.swing.JComboBox<String> Jcombo_cod_sede;
    public javax.swing.JComboBox<String> Jcombo_products;
    public javax.swing.JComboBox<String> Jcombo_urg_nivel;
    public com.toedter.calendar.JDateChooser JdFecha;
    public javax.swing.JTable TABLA_DATOS;
    public javax.swing.JButton btn_return;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField txt_busqueda;
    public javax.swing.JTextField txt_cod_venta2;
    // End of variables declaration//GEN-END:variables
class FondoPanel extends JPanel
    {
        private Image imagen;
        
        @Override
        public void paint(Graphics g)
        {
            imagen = new ImageIcon(getClass().getResource("/Pictures/ventas.png")).getImage();
            
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            
            setOpaque(false);
            
            super.paint(g);
        }
    }
}
